# -*- coding: utf-8 -*-
"""emotionRecognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/187QZtVEMTwUYvHVPvnIRqhT8y8utkEJx
"""

# install requirement
!pip install --upgrade diffusers[torch]
!pip install transformers

from diffusers import DiffusionPipeline
import torch

pipeline = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)
pipeline.to("cuda")

import random
import matplotlib.pyplot as plt
import os

os.makedirs('/content/face/happy', exist_ok=True)
os.makedirs('/content/face/sad', exist_ok=True)
os.makedirs('/content/face/surprised', exist_ok=True)
os.makedirs('/content/face/angry', exist_ok=True)

ethnicities = ['a pakistan','a indian','a black','a white','a korean']
genders = ['male','female']
emotions_prompts = {'happy': 'smiling',
                    'sad': 'frowning, sad face expression, crying',
                    'surprised': 'surprised, opened mouth, raised eyebrows',
                    'angry':'angry'}

iterations = 0
max_iterations = 10  # Set the maximum number of iterations here

for j in range(max_iterations):
    for emotion in emotions_prompts.keys():
        emotion_promot = emotions_prompts[emotion]
        enthnicity = random.choice(ethnicities)
        gender = random.choice(genders)
        #print (enthnicity, gender, emotion_promot )
        prompt = 'Medium-shot portrait of a {} person {}, front view, looking at the camera, color photography, '.format(enthnicity, gender) +\
            'photorealistic, hyperrealistic, realistic, incredibly detailed, crisp focus, digital art, depth of field, 50mm, 8k'
        negative_prompt = '3d, cartoon, anime, sketches, (worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality,((monochrome)),' + \
                        '((grayscale)) Low Quality, worst Quality, plastic, fake, disfigured, deformed, blurry, bad anatomy, blurred, watermark, grainy, signature'
        img = pipeline(prompt, negative_prompt=negative_prompt).images[0]

        img.save('/content/face/{}/{}.png'.format(emotion, str(j).zfill(4)))

        plt.imshow(img)
        plt.show()

        iterations += 1
        if iterations >= max_iterations:
            break
    else:
        continue
    break  # This break is for the outer loop

!zip -r faces.zip /content/face

from google.colab import drive

drive.mount('/content/gdrive')

!scp '/content/faces.zip' '/content/gdrive/My Drive/download/faces1.zip'