# -*- coding: utf-8 -*-
"""Untitled55.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZTLWAt8eQ5_3WhQX6VZsO0WLuBTbPeeZ
"""

!pip install markovify

import markovify
import pandas as pd
df = pd.read_csv("/content/IMDB Dataset.csv")

df = pd.read_csv("/content/IMDB Dataset.csv")

# Ensure the column 'review' exists
if 'review' in df.columns:
    N = 100
    review_subset = df["review"].iloc[:N]  # Use iloc for slicing

    # Combine the reviews into a single text
    text = " ".join(review for review in review_subset)

    # Create the Markov chain model
    markov_chain_model = markovify.Text(text)

    # Generate and print 50 sentences
    for i in range(50):
        print(markov_chain_model.make_sentence())
else:
    print("Column 'review' not found in DataFrame")

for i in range(20):
    print(markov_chain_model.make_sentence())

for i in range (3):
  print(markov_chain_model.make_short_sentence(140))

